/**
 * Therapist Report Generation API
 * Generate PDF/CSV reports for therapist activity and metrics
 * HIPAA Compliant: Requires authentication and enforces organization boundaries
 */

import type { NextRequest } from 'next/server';
import { and, count, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { db } from '@/libs/DB';
import { auditLogs, mediaLibrary, sessions, storyPages, users } from '@/models/Schema';
import { handleAuthError, requireAdmin } from '@/utils/AuthHelpers';

/**
 * GET /api/therapists/[id]/report - Generate therapist activity report
 *
 * Query Parameters:
 * - format: 'pdf' | 'csv' (default: 'pdf')
 *
 * Access Control:
 * - Org admins: Can only generate reports for therapists in their organization
 * - Super admins: Can generate reports for any therapist
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    // HIPAA: Require org admin or super admin
    const authUser = await requireAdmin(request);
    const { id } = await params;

    const { searchParams } = new URL(request.url);
    const format = searchParams.get('format') || 'pdf';

    // Fetch therapist
    const therapist = await db.query.users.findFirst({
      where: (users, { eq }) => eq(users.id, id),
    });

    if (!therapist) {
      return NextResponse.json(
        { error: 'Therapist not found' },
        { status: 404 },
      );
    }

    // Ensure therapist is actually a therapist role
    if (therapist.role !== 'therapist') {
      return NextResponse.json(
        { error: 'User is not a therapist' },
        { status: 400 },
      );
    }

    // Organization boundary enforcement
    if (authUser.role === 'org_admin') {
      if (therapist.organizationId !== authUser.organizationId) {
        return NextResponse.json(
          { error: 'Forbidden: Cannot generate reports for therapists outside your organization' },
          { status: 403 },
        );
      }
    }

    // Gather comprehensive metrics
    const totalPatientsResult = await db
      .select({ count: count() })
      .from(users)
      .where(
        and(
          eq(users.role, 'patient'),
          eq(users.therapistId, therapist.id),
        ),
      );
    const totalPatients = Number(totalPatientsResult[0]?.count || 0);

    const totalSessionsResult = await db
      .select({ count: count() })
      .from(sessions)
      .where(eq(sessions.therapistId, therapist.id));
    const totalSessions = Number(totalSessionsResult[0]?.count || 0);

    const storyPagesCreatedResult = await db
      .select({ count: count() })
      .from(storyPages)
      .where(eq(storyPages.createdByTherapistId, therapist.id));
    const storyPagesCreated = Number(storyPagesCreatedResult[0]?.count || 0);

    const mediaGeneratedResult = await db
      .select({ count: count() })
      .from(mediaLibrary)
      .where(eq(mediaLibrary.createdByTherapistId, therapist.id));
    const mediaGenerated = Number(mediaGeneratedResult[0]?.count || 0);

    const activityLogResult = await db
      .select({ count: count() })
      .from(auditLogs)
      .where(eq(auditLogs.userId, therapist.id));
    const totalActivityEntries = Number(activityLogResult[0]?.count || 0);

    // Generate report data
    const reportData = {
      therapist: {
        name: therapist.name,
        email: therapist.email,
        licenseNumber: therapist.licenseNumber,
        specialty: therapist.specialty,
        status: therapist.status,
        createdAt: therapist.createdAt,
        lastLoginAt: therapist.lastLoginAt,
      },
      metrics: {
        totalPatients,
        totalSessions,
        storyPagesCreated,
        mediaGenerated,
        totalActivityEntries,
      },
      generatedAt: new Date().toISOString(),
      generatedBy: authUser.email,
    };

    // Return format based on query parameter
    if (format === 'csv') {
      // Generate CSV report
      const csv = [
        // Header
        'Metric,Value',
        `Therapist Name,${reportData.therapist.name}`,
        `Email,${reportData.therapist.email}`,
        `License Number,${reportData.therapist.licenseNumber || 'N/A'}`,
        `Specialty,${reportData.therapist.specialty || 'N/A'}`,
        `Status,${reportData.therapist.status}`,
        `Account Created,${reportData.therapist.createdAt}`,
        `Last Login,${reportData.therapist.lastLoginAt || 'Never'}`,
        '',
        'Activity Metrics,',
        `Total Patients,${reportData.metrics.totalPatients}`,
        `Total Sessions,${reportData.metrics.totalSessions}`,
        `Story Pages Created,${reportData.metrics.storyPagesCreated}`,
        `Media Generated,${reportData.metrics.mediaGenerated}`,
        `Total Activity Entries,${reportData.metrics.totalActivityEntries}`,
        '',
        `Report Generated At,${reportData.generatedAt}`,
        `Generated By,${reportData.generatedBy}`,
      ].join('\n');

      return new NextResponse(csv, {
        status: 200,
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename="therapist-report-${therapist.id}-${Date.now()}.csv"`,
        },
      });
    } else {
      // Generate HTML report (simpler alternative to PDF generation)
      // In production, you'd use a library like puppeteer or pdfkit
      const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Therapist Activity Report - ${therapist.name}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      color: #333;
    }
    h1 {
      color: #4F46E5;
      border-bottom: 3px solid #4F46E5;
      padding-bottom: 10px;
    }
    h2 {
      color: #6366F1;
      margin-top: 30px;
      margin-bottom: 15px;
    }
    .info-grid {
      display: grid;
      grid-template-columns: 200px 1fr;
      gap: 10px;
      margin-bottom: 20px;
    }
    .label {
      font-weight: bold;
      color: #666;
    }
    .value {
      color: #333;
    }
    .metric-box {
      background: #F3F4F6;
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 10px;
    }
    .metric-label {
      font-size: 14px;
      color: #666;
      margin-bottom: 5px;
    }
    .metric-value {
      font-size: 28px;
      font-weight: bold;
      color: #4F46E5;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #E5E7EB;
      font-size: 12px;
      color: #999;
    }
    @media print {
      body {
        margin: 0;
        padding: 20px;
      }
    }
  </style>
</head>
<body>
  <h1>Therapist Activity Report</h1>

  <h2>Therapist Information</h2>
  <div class="info-grid">
    <div class="label">Name:</div>
    <div class="value">${reportData.therapist.name}</div>

    <div class="label">Email:</div>
    <div class="value">${reportData.therapist.email}</div>

    <div class="label">License Number:</div>
    <div class="value">${reportData.therapist.licenseNumber || 'N/A'}</div>

    <div class="label">Specialty:</div>
    <div class="value">${reportData.therapist.specialty || 'N/A'}</div>

    <div class="label">Status:</div>
    <div class="value">${reportData.therapist.status}</div>

    <div class="label">Account Created:</div>
    <div class="value">${new Date(reportData.therapist.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })}</div>

    <div class="label">Last Login:</div>
    <div class="value">${reportData.therapist.lastLoginAt
      ? new Date(reportData.therapist.lastLoginAt).toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
        })
      : 'Never'}</div>
  </div>

  <h2>Activity Metrics</h2>

  <div class="metric-box">
    <div class="metric-label">Total Patients</div>
    <div class="metric-value">${reportData.metrics.totalPatients}</div>
  </div>

  <div class="metric-box">
    <div class="metric-label">Total Sessions</div>
    <div class="metric-value">${reportData.metrics.totalSessions}</div>
  </div>

  <div class="metric-box">
    <div class="metric-label">Story Pages Created</div>
    <div class="metric-value">${reportData.metrics.storyPagesCreated}</div>
  </div>

  <div class="metric-box">
    <div class="metric-label">Media Generated</div>
    <div class="metric-value">${reportData.metrics.mediaGenerated}</div>
  </div>

  <div class="metric-box">
    <div class="metric-label">Total Activity Entries (HIPAA Audit Log)</div>
    <div class="metric-value">${reportData.metrics.totalActivityEntries}</div>
  </div>

  <div class="footer">
    <p>Report Generated: ${new Date(reportData.generatedAt).toLocaleString('en-US')}</p>
    <p>Generated By: ${reportData.generatedBy}</p>
    <p>This report contains Protected Health Information (PHI) and must be handled in accordance with HIPAA regulations.</p>
  </div>
</body>
</html>
      `.trim();

      return new NextResponse(html, {
        status: 200,
        headers: {
          'Content-Type': 'text/html',
        },
      });
    }
  } catch (error) {
    console.error('Failed to generate therapist report:', error);
    return handleAuthError(error);
  }
}
