/**
 * Story Page Generator Service
 * Auto-generate story pages from module-analyzed sessions
 */

import { and, desc, eq, isNull } from 'drizzle-orm';
import { db } from '@/libs/DB';
import {
  mediaLibrarySchema,
  pageBlocksSchema,
  storyPagesSchema,
} from '@/models/Schema';
import { sendStoryPageNotification } from './EmailService';
import { getModuleById } from './ModuleService';
import { getSessionModuleBySessionId, linkStoryPageToSessionModule } from './SessionService';

/**
 * Generate complete story page from module
 */
export async function generateStoryPageFromModule(params: {
  moduleId: string;
  sessionId: string;
  patientId: string;
  therapistId: string;
  includeMedia?: boolean;
  sendNotification?: boolean;
  customTitle?: string;
  customMessage?: string;
}) {
  // 1. Fetch module
  const { module: treatmentModule } = await getModuleById(params.moduleId);

  if (!treatmentModule) {
    throw new Error('Module not found');
  }

  // 2. Fetch session-module analysis
  const sessionModule = await getSessionModuleBySessionId(params.sessionId);

  if (!sessionModule) {
    throw new Error('Session module assignment not found');
  }

  // 3. Generate page title
  const pageTitle
    = params.customTitle
      || generatePageTitle(treatmentModule.name, sessionModule.aiAnalysisResult);

  // 4. Create story page
  const [storyPage] = await db
    .insert(storyPagesSchema)
    .values({
      patientId: params.patientId,
      createdByTherapistId: params.therapistId,
      title: pageTitle,
      description: treatmentModule.description,
      status: 'draft', // Start as draft, therapist can review before publishing
      visibility: 'private',
      moduleId: params.moduleId,
      autoGenerated: true,
      generationSource: 'module_auto',
      createdAt: new Date(),
      updatedAt: new Date(),
    })
    .returning();

  if (!storyPage) {
    throw new Error('Failed to create story page');
  }

  // 5. Build page blocks
  const blocks = await buildPageBlocks({
    pageId: storyPage.id,
    sessionId: params.sessionId,
    patientId: params.patientId,
    includeMedia: params.includeMedia || false,
    aiAnalysisResult: sessionModule.aiAnalysisResult,
  });

  // 8. Link story page to session-module
  await linkStoryPageToSessionModule(params.sessionId, storyPage.id);

  // 9. Send notification (if requested and page is published)
  let emailNotification = null;
  if (params.sendNotification && storyPage.status === 'published') {
    // Get patient and therapist details for notification
    const patient = await db.query.users.findFirst({
      where: (users, { eq }) => eq(users.id, params.patientId),
    });

    const therapist = await db.query.users.findFirst({
      where: (users, { eq }) => eq(users.id, params.therapistId),
    });

    if (patient && patient.email && therapist) {
      const storyPageUrl = `${process.env.NEXT_PUBLIC_APP_URL}/patient/story/${storyPage.id}`;

      emailNotification = await sendStoryPageNotification({
        patientUserId: params.patientId,
        patientEmail: patient.email,
        patientName: patient.name,
        therapistName: therapist.name,
        storyPageId: storyPage.id,
        storyPageTitle: params.customTitle || treatmentModule.name,
        storyPageUrl,
        customMessage: params.customMessage,
      });
    }
  }

  return {
    storyPage,
    blocks,
    emailNotification,
  };
}

/**
 * Build page blocks from session content and AI analysis
 */
async function buildPageBlocks(params: {
  pageId: string;
  sessionId: string;
  patientId: string;
  includeMedia: boolean;
  aiAnalysisResult: any;
}) {
  const blocks = [];
  let sequenceNumber = 1;

  // 1. Add intro text block from AI analysis summary
  if (params.aiAnalysisResult?.thematicSummary) {
    const [introBlock] = await db
      .insert(pageBlocksSchema)
      .values({
        pageId: params.pageId,
        blockType: 'text',
        sequenceNumber: sequenceNumber++,
        textContent: params.aiAnalysisResult.thematicSummary,
        settings: { style: 'intro' },
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      .returning();

    blocks.push(introBlock);
  }

  // 2. Add media blocks (if includeMedia and media available)
  if (params.includeMedia) {
    // Query media_library for media from this session
    const sessionMedia = await db
      .select()
      .from(mediaLibrarySchema)
      .where(
        and(
          eq(mediaLibrarySchema.sourceSessionId, params.sessionId),
          eq(mediaLibrarySchema.patientId, params.patientId),
          isNull(mediaLibrarySchema.deletedAt),
        ),
      )
      .orderBy(desc(mediaLibrarySchema.createdAt))
      .limit(5); // Limit to 5 most recent media items

    for (const media of sessionMedia) {
      const blockType = media.mediaType === 'image' ? 'image' : media.mediaType === 'video' ? 'video' : null;
      if (!blockType) continue; // Skip non-image/video media

      const [mediaBlock] = await db
        .insert(pageBlocksSchema)
        .values({
          pageId: params.pageId,
          blockType,
          sequenceNumber: sequenceNumber++,
          mediaId: media.id,
          settings: {
            caption: media.description || media.title,
            thumbnailUrl: media.thumbnailUrl,
            width: media.widthPx,
            height: media.heightPx,
          },
          createdAt: new Date(),
          updatedAt: new Date(),
        })
        .returning();

      if (mediaBlock) {
        blocks.push(mediaBlock);
      }
    }
  }

  // 3. Add quotes as text blocks
  if (params.aiAnalysisResult?.patientQuotes && Array.isArray(params.aiAnalysisResult.patientQuotes)) {
    for (const quote of params.aiAnalysisResult.patientQuotes) {
      const [quoteBlock] = await db
        .insert(pageBlocksSchema)
        .values({
          pageId: params.pageId,
          blockType: 'text',
          sequenceNumber: sequenceNumber++,
          textContent: `"${quote}"`,
          settings: { style: 'quote' },
          createdAt: new Date(),
          updatedAt: new Date(),
        })
        .returning();

      blocks.push(quoteBlock);
    }
  }

  // 4. Add closing text from clinical insights
  if (params.aiAnalysisResult?.clinicalInsights && Array.isArray(params.aiAnalysisResult.clinicalInsights)) {
    const insightsText = params.aiAnalysisResult.clinicalInsights.join('\n\n');

    const [closingBlock] = await db
      .insert(pageBlocksSchema)
      .values({
        pageId: params.pageId,
        blockType: 'text',
        sequenceNumber: sequenceNumber++,
        textContent: insightsText,
        settings: { style: 'insight' },
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      .returning();

    blocks.push(closingBlock);
  }

  return blocks;
}

/**
 * Generate page title from module name and AI analysis
 */
function generatePageTitle(moduleName: string, aiAnalysisResult: any): string {
  // Try to create a personalized title from AI analysis
  if (aiAnalysisResult?.thematicSummary) {
    const summary = aiAnalysisResult.thematicSummary as string;
    const firstSentence = summary.split('.')[0];

    if (firstSentence && firstSentence.length > 10 && firstSentence.length < 60) {
      return firstSentence;
    }
  }

  // Fallback to module-based title
  return `Your ${moduleName} Journey`;
}

/**
 * Publish auto-generated story page and send notification
 */
export async function publishAndNotify(params: {
  storyPageId: string;
  patientId: string;
  patientEmail: string;
  patientName: string;
  therapistName: string;
  customMessage?: string;
}) {
  // 1. Update page status to published
  const [storyPage] = await db
    .update(storyPagesSchema)
    .set({
      status: 'published',
      publishedAt: new Date(),
      updatedAt: new Date(),
    })
    .where(eq(storyPagesSchema.id, params.storyPageId))
    .returning();

  if (!storyPage) {
    throw new Error('Failed to update story page status');
  }

  // 2. Send email notification
  const storyPageUrl = `${process.env.NEXT_PUBLIC_APP_URL}/patient/story/${params.storyPageId}`;

  const emailNotification = await sendStoryPageNotification({
    patientEmail: params.patientEmail,
    patientName: params.patientName,
    patientUserId: params.patientId,
    therapistName: params.therapistName,
    storyPageTitle: storyPage.title,
    storyPageUrl,
    storyPageId: params.storyPageId,
    customMessage: params.customMessage,
  });

  if (!emailNotification) {
    throw new Error('Failed to send email notification');
  }

  // 3. Link email notification to story page
  await db
    .update(storyPagesSchema)
    .set({
      emailNotificationId: emailNotification.id,
      updatedAt: new Date(),
    })
    .where(eq(storyPagesSchema.id, params.storyPageId));

  return {
    storyPage,
    emailNotification,
  };
}
