/**
 * Story Page Generator Service
 * Auto-generate story pages from module-analyzed sessions
 */

import { and, desc, eq, isNull } from 'drizzle-orm';
import { db } from '@/libs/DB';
import {
  mediaLibrarySchema,
  pageBlocksSchema,
  reflectionQuestionsSchema,
  storyPagesSchema,
  surveyQuestionsSchema,
} from '@/models/Schema';
import { sendStoryPageNotification } from './EmailService';
import { getModuleById } from './ModuleService';
import { getSessionModuleBySessionId, linkStoryPageToSessionModule } from './SessionService';

/**
 * Generate complete story page from module
 */
export async function generateStoryPageFromModule(params: {
  moduleId: string;
  sessionId: string;
  patientId: string;
  therapistId: string;
  includeMedia?: boolean;
  sendNotification?: boolean;
  customTitle?: string;
}) {
  // 1. Fetch module with templates
  const { module, reflectionTemplate, surveyTemplate } = await getModuleById(params.moduleId);

  if (!module) {
    throw new Error('Module not found');
  }

  // 2. Fetch session-module analysis
  const sessionModule = await getSessionModuleBySessionId(params.sessionId);

  if (!sessionModule) {
    throw new Error('Session module assignment not found');
  }

  // 3. Generate page title
  const pageTitle
    = params.customTitle
      || generatePageTitle(module.name, sessionModule.aiAnalysisResult);

  // 4. Create story page
  const [storyPage] = await db
    .insert(storyPagesSchema)
    .values({
      patientId: params.patientId,
      createdByTherapistId: params.therapistId,
      title: pageTitle,
      description: module.description,
      status: 'draft', // Start as draft, therapist can review before publishing
      visibility: 'private',
      moduleId: params.moduleId,
      autoGenerated: true,
      generationSource: 'module_auto',
      createdAt: new Date(),
      updatedAt: new Date(),
    })
    .returning();

  // 5. Build page blocks
  const blocks = await buildPageBlocks({
    pageId: storyPage.id,
    sessionId: params.sessionId,
    includeMedia: params.includeMedia || false,
    aiAnalysisResult: sessionModule.aiAnalysisResult,
  });

  // 6. Add reflection questions block (if template exists)
  if (reflectionTemplate) {
    const reflectionBlock = await createReflectionBlock({
      pageId: storyPage.id,
      reflectionTemplate,
      sequenceNumber: blocks.length + 1,
    });
    blocks.push(reflectionBlock);
  }

  // 7. Add survey questions block (if template exists)
  if (surveyTemplate) {
    const surveyBlock = await createSurveyBlock({
      pageId: storyPage.id,
      surveyTemplate,
      sequenceNumber: blocks.length + 1,
    });
    blocks.push(surveyBlock);
  }

  // 8. Link story page to session-module
  await linkStoryPageToSessionModule(params.sessionId, storyPage.id);

  // 9. Send notification (if requested and page is published)
  let emailNotification = null;
  if (params.sendNotification && storyPage.status === 'published') {
    // Get patient details for notification
    const patient = await db.query.users.findFirst({
      where: (users, { eq }) => eq(users.id, params.patientId),
    });

    if (patient && patient.email) {
      emailNotification = await sendStoryPageNotification({
        patientId: params.patientId,
        patientEmail: patient.email,
        patientName: patient.name,
        storyPageId: storyPage.id,
        storyPageTitle: params.customTitle || module.name,
        customMessage: params.customMessage,
      });
    }
  }

  return {
    storyPage,
    blocks,
    emailNotification,
  };
}

/**
 * Build page blocks from session content and AI analysis
 */
async function buildPageBlocks(params: {
  pageId: string;
  sessionId: string;
  includeMedia: boolean;
  aiAnalysisResult: any;
}) {
  const blocks = [];
  let sequenceNumber = 1;

  // 1. Add intro text block from AI analysis summary
  if (params.aiAnalysisResult?.thematicSummary) {
    const [introBlock] = await db
      .insert(pageBlocksSchema)
      .values({
        pageId: params.pageId,
        blockType: 'text',
        sequenceNumber: sequenceNumber++,
        textContent: params.aiAnalysisResult.thematicSummary,
        settings: { style: 'intro' },
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      .returning();

    blocks.push(introBlock);
  }

  // 2. Add media blocks (if includeMedia and media available)
  if (params.includeMedia) {
    // Query media_library for media from this session
    const sessionMedia = await db
      .select()
      .from(mediaLibrarySchema)
      .where(
        and(
          eq(mediaLibrarySchema.sourceSessionId, params.sessionId),
          eq(mediaLibrarySchema.patientId, params.patientId),
          isNull(mediaLibrarySchema.deletedAt),
        ),
      )
      .orderBy(desc(mediaLibrarySchema.createdAt))
      .limit(5); // Limit to 5 most recent media items

    for (const media of sessionMedia) {
      const blockType = media.mediaType === 'image' ? 'image' : media.mediaType === 'video' ? 'video' : null;
      if (!blockType) continue; // Skip non-image/video media

      const [mediaBlock] = await db
        .insert(pageBlocksSchema)
        .values({
          pageId: params.pageId,
          blockType,
          sequenceNumber: sequenceNumber++,
          mediaUrl: media.mediaUrl,
          mediaCaption: media.description || media.title,
          settings: {
            thumbnailUrl: media.thumbnailUrl,
            width: media.widthPx,
            height: media.heightPx,
          },
          createdAt: new Date(),
          updatedAt: new Date(),
        })
        .returning();

      blocks.push(mediaBlock);
    }
  }

  // 3. Add quotes as text blocks
  if (params.aiAnalysisResult?.patientQuotes && Array.isArray(params.aiAnalysisResult.patientQuotes)) {
    for (const quote of params.aiAnalysisResult.patientQuotes) {
      const [quoteBlock] = await db
        .insert(pageBlocksSchema)
        .values({
          pageId: params.pageId,
          blockType: 'text',
          sequenceNumber: sequenceNumber++,
          textContent: `"${quote}"`,
          settings: { style: 'quote' },
          createdAt: new Date(),
          updatedAt: new Date(),
        })
        .returning();

      blocks.push(quoteBlock);
    }
  }

  // 4. Add closing text from clinical insights
  if (params.aiAnalysisResult?.clinicalInsights && Array.isArray(params.aiAnalysisResult.clinicalInsights)) {
    const insightsText = params.aiAnalysisResult.clinicalInsights.join('\n\n');

    const [closingBlock] = await db
      .insert(pageBlocksSchema)
      .values({
        pageId: params.pageId,
        blockType: 'text',
        sequenceNumber: sequenceNumber++,
        textContent: insightsText,
        settings: { style: 'insight' },
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      .returning();

    blocks.push(closingBlock);
  }

  return blocks;
}

/**
 * Create reflection block and clone questions from template
 */
async function createReflectionBlock(params: {
  pageId: string;
  reflectionTemplate: any;
  sequenceNumber: number;
}) {
  // 1. Create reflection block
  const [block] = await db
    .insert(pageBlocksSchema)
    .values({
      pageId: params.pageId,
      blockType: 'reflection',
      sequenceNumber: params.sequenceNumber,
      textContent: null,
      settings: {
        templateId: params.reflectionTemplate.id,
        templateTitle: params.reflectionTemplate.title,
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    })
    .returning();

  // 2. Clone questions from template
  const templateQuestions = params.reflectionTemplate.questions as any[];

  if (Array.isArray(templateQuestions)) {
    for (let i = 0; i < templateQuestions.length; i++) {
      const q = templateQuestions[i];

      await db.insert(reflectionQuestionsSchema).values({
        blockId: block.id,
        questionText: q.text,
        questionType: q.type || 'open_text',
        options: q.options || null,
        sequenceNumber: i + 1,
        createdAt: new Date(),
      });
    }
  }

  return block;
}

/**
 * Create survey block and clone questions from template
 */
async function createSurveyBlock(params: {
  pageId: string;
  surveyTemplate: any;
  sequenceNumber: number;
}) {
  // 1. Create survey block
  const [block] = await db
    .insert(pageBlocksSchema)
    .values({
      pageId: params.pageId,
      blockType: 'survey',
      sequenceNumber: params.sequenceNumber,
      textContent: null,
      settings: {
        templateId: params.surveyTemplate.id,
        templateTitle: params.surveyTemplate.title,
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    })
    .returning();

  // 2. Clone questions from template
  const templateQuestions = params.surveyTemplate.questions as any[];

  if (Array.isArray(templateQuestions)) {
    for (let i = 0; i < templateQuestions.length; i++) {
      const q = templateQuestions[i];

      await db.insert(surveyQuestionsSchema).values({
        blockId: block.id,
        questionText: q.text,
        questionType: q.type,
        scaleMin: q.scaleMin || null,
        scaleMax: q.scaleMax || null,
        scaleMinLabel: q.scaleMinLabel || null,
        scaleMaxLabel: q.scaleMaxLabel || null,
        options: q.options || null,
        sequenceNumber: i + 1,
        createdAt: new Date(),
      });
    }
  }

  return block;
}

/**
 * Generate page title from module name and AI analysis
 */
function generatePageTitle(moduleName: string, aiAnalysisResult: any): string {
  // Try to create a personalized title from AI analysis
  if (aiAnalysisResult?.thematicSummary) {
    const summary = aiAnalysisResult.thematicSummary as string;
    const firstSentence = summary.split('.')[0];

    if (firstSentence.length > 10 && firstSentence.length < 60) {
      return firstSentence;
    }
  }

  // Fallback to module-based title
  return `Your ${moduleName} Journey`;
}

/**
 * Publish auto-generated story page and send notification
 */
export async function publishAndNotify(params: {
  storyPageId: string;
  patientId: string;
  patientEmail: string;
  patientName: string;
  therapistName: string;
  customMessage?: string;
}) {
  // 1. Update page status to published
  const [storyPage] = await db
    .update(storyPagesSchema)
    .set({
      status: 'published',
      publishedAt: new Date(),
      updatedAt: new Date(),
    })
    .where(eq => eq(storyPagesSchema.id, params.storyPageId))
    .returning();

  // 2. Send email notification
  const storyPageUrl = `${process.env.NEXT_PUBLIC_APP_URL}/patient/story/${params.storyPageId}`;

  const emailNotification = await sendStoryPageNotification({
    patientEmail: params.patientEmail,
    patientName: params.patientName,
    patientUserId: params.patientId,
    therapistName: params.therapistName,
    storyPageTitle: storyPage.title,
    storyPageUrl,
    storyPageId: params.storyPageId,
    customMessage: params.customMessage,
  });

  // 3. Link email notification to story page
  await db
    .update(storyPagesSchema)
    .set({
      emailNotificationId: emailNotification.id,
      updatedAt: new Date(),
    })
    .where(eq => eq(storyPagesSchema.id, params.storyPageId));

  return {
    storyPage,
    emailNotification,
  };
}
