/**
 * Analyze Session with Module API
 * Run AI analysis using module-specific prompt
 */

import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import {
  getSessionWithModule,
  updateSessionModuleAnalysis,
} from '@/services/SessionService';
import { handleAuthError, requireAuth } from '@/utils/AuthHelpers';
import { analyzeSessionWithModuleSchema } from '@/validations/ModuleValidation';

/**
 * POST /api/sessions/[id]/analyze-with-module
 * Run AI analysis using the assigned module's prompt
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params;
    const user = await requireAuth(request);

    // Only therapists and admins can run analysis
    if (user.role === 'patient') {
      return NextResponse.json(
        { error: 'Forbidden: Patients cannot run analysis' },
        { status: 403 },
      );
    }

    const body = await request.json();
    // Validate request body (validation result currently unused but kept for consistency)
  analyzeSessionWithModuleSchema.parse(body);

    // Get session with module
    const { session, module, sessionModule } = await getSessionWithModule(id);

    if (!session) {
      return NextResponse.json({ error: 'Session not found' }, { status: 404 });
    }

    if (!module || !sessionModule) {
      return NextResponse.json(
        { error: 'No module assigned to this session. Please assign a module first.' },
        { status: 400 },
      );
    }

    // TODO: Verify therapist has access to the session

    // TODO: Fetch transcript for the session
    // const transcript = await getTranscriptBySessionId(id);

    // TODO: Call OpenAI API with module's AI prompt
    // For now, we'll create a placeholder analysis result
    const analysisResult = {
      thematicSummary: 'Placeholder: This will be generated by AI using the module-specific prompt',
      visualSceneSuggestions: [
        'Scene suggestion 1',
        'Scene suggestion 2',
      ],
      patientQuotes: [
        'Sample quote from transcript',
      ],
      metaphors: [
        'Identified metaphor 1',
      ],
      emotionalShifts: [
        'Emotional shift 1',
      ],
      clinicalInsights: [
        'Clinical insight 1',
      ],
      analyzedAt: new Date().toISOString(),
      moduleUsed: module.name,
      promptUsed: module.aiPromptText,
    };

    // Update session module with analysis result
    const updatedSessionModule = await updateSessionModuleAnalysis(
      id,
      analysisResult,
    );

    return NextResponse.json({
      message: 'Analysis completed successfully',
      analysis: analysisResult,
      sessionModule: updatedSessionModule,
    });
  } catch (error) {
    if (error instanceof Error && error.message.includes('validation')) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }
    return handleAuthError(error);
  }
}
